/*ALTER TABLE [dbo].[EntriesInTags]
    ADD CONSTRAINT [PK_EntriesInTags] PRIMARY KEY CLUSTERED ([EntryId] ASC, [TagId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

