ALTER TABLE [dbo].[PostsInCategories]
    ADD CONSTRAINT [PK_EntriesInCategories] PRIMARY KEY CLUSTERED ([PostId] ASC, [CategoryId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

