//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace KeaDAL
{
    public partial class Auth_Roles
    {
        public Auth_Roles()
        {
            this.Auth_Users = new HashSet<Auth_Users>();
        }
    
        public int Id { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<Auth_Users> Auth_Users { get; set; }
    }
    
}
