//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace KeaDAL
{
    public partial class auth_Roles
    {
        public auth_Roles()
        {
            this.auth_Users = new HashSet<auth_Users>();
        }
    
        public int Id { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<auth_Users> auth_Users { get; set; }
    }
    
}
