//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace KeaDAL
{
    public partial class PostShort
    {
        public Nullable<int> Id { get; set; }
        public string Title { get; set; }
        public string AuthorName { get; set; }
        public bool Visible { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string FullContent { get; set; }
        public string CategoryName { get; set; }
        public string LinkToOriginal { get; set; }
    }
    
}
